---
- block:
  - name: Add GPG key to RPM database on Fedora
    rpm_key:
      key: "{{ item.rpm_key }}"
      state: present
    with_items: "{{ bulk_packages_new_repos }}"
    when: bulk_packages_new_repos is defined

  - name: Install new repository from RPM on Fedora
    dnf:
      name: "{{ item.location }}"
      state: present
    with_items: "{{ bulk_packages_new_repos }}"
    when: bulk_packages_new_repos is defined

  - name: Remove unwanted packages from Fedora
    dnf:
      name: "{{ bulk_packages_absent }}"
      state: absent
      autoremove: true
    when: bulk_packages_absent is defined

  - name: Install packages on Fedora
    dnf:
      name: "{{ bulk_packages_present }}"
      state: present
    when: bulk_packages_present is defined
  become: true
