---
- block:
  - name: Remove unwanted packages from Fedora
    dnf:
      name: "{{ bulk_packages_absent }}"
      state: absent
      autoremove: true
    when: bulk_packages_absent is defined

  - name: Install packages on Fedora
    dnf:
      name: "{{ bulk_packages_present }}"
      state: present
    when: bulk_packages_present is defined
  become: true
