---
- import_tasks: bulk_Fedora_packages.yml
  when: ansible_distribution == "Fedora"

- import_tasks: bulk_RedHat_packages.yml
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"
