---
# Consult defaults/main.yml to learn about the role variables.

- block:
  - name: Remove unwanted packages using APT
    apt:
      name: "{{ unwanted_packages_list }}"
      state: absent
    when: ansible_pkg_mgr == "apt"
    register: unwanted_packages_no_generic

  - name: Remove unwanted packages using DNF
    dnf:
      name: "{{ unwanted_packages_list }}"
      state: absent
      autoremove: true
    when: ansible_pkg_mgr == "dnf"
    register: unwanted_packages_no_generic

  - name: Remove unwanted packages using YUM
    yum:
      name: "{{ unwanted_packages_list }}"
      state: absent
    when: ansible_pkg_mgr == "yum"
    register: unwanted_packages_no_generic

  - name: Remove unwanted packages using available package manager
    package:
      name: "{{ unwanted_packages_list }}"
      state: absent
    when: unwanted_packages_no_generic is undefined
  become: true
